package com.Java.Universal.Week2;

import java.util.Scanner;

public class Lucas_Series_StringQ5 {
    public static void main(String[] args) {
        Scanner in = new Scanner(System.in);
        System.out.println("Enter your number :");
        int LN = in.nextInt();
        int next;
        int l1 = -1;
        int l2 = 1;
        for (int i=0 ; i<LN; i++){
            next = l1+l2;
            l1 = l2;
            l2= next;
            System.out.print(next+" ");
        }

    }
}
/*The Lucas series is a sequence of numbers similar to the Fibonacci sequence. It starts with two initial terms, \( L_0 \) and \( L_1 \), and each subsequent term is the sum of the two preceding terms.

Here's how it works:

1. **Initial Terms**: The Lucas series starts with two initial terms, usually \( L_0 = 2 \) and \( L_1 = 1 \).

2. **Generating Sequence**: After the initial terms, each subsequent term is generated by adding the two preceding terms. So, \( L_2 = L_0 + L_1 \), \( L_3 = L_1 + L_2 \), and so on.

3. **Example**: Let's start with \( L_0 = 2 \) and \( L_1 = 1 \). Then,
   - \( L_2 = L_0 + L_1 = 2 + 1 = 3 \)
   - \( L_3 = L_1 + L_2 = 1 + 3 = 4 \)
   - \( L_4 = L_2 + L_3 = 3 + 4 = 7 \)
   - \( L_5 = L_3 + L_4 = 4 + 7 = 11 \)
   - And so on...

The Lucas series starts as follows: 2, 1, 3, 4, 7, 11, 18, 29, 47, ...

Just like the Fibonacci series, the Lucas series also exhibits some interesting mathematical properties and appears in various contexts in mathematics and nature.
*/